logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rise_up
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB