logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raise_up
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub