logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raise_up
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update